# This is a basic workflow to help you get started with Actions
name: CI-CD-Pipeline-to-AWS-ElasticBeanstalk
env: 
  EB_PACKAGE_S3_BUCKET_NAME : "flusk-application-packages"
  EB_APPLICATION_NAME       : "MyFlusk"
  EB_ENVIRONMENT_NAME       : "MyFlusk-env"
  DEPLOY_PACKAGE_NAME       : "flusk_app_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-west-2"

# Controls when the workflow will run
on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  my-ci-part:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1
      
      - name: Create ZIP deployment package
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
